version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: on-failure
    ports:
      - "8043:8043"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      PORT: 8043
      TMDB_API_Key: ${TMDB_API_Key}
      Ticketmaster_Consumer_Key: ${Ticketmaster_Consumer_Key}
      Foursquare_SERVICE_API: ${Foursquare_SERVICE_API}
    depends_on:
      - db

volumes:
  pgdata:
